USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

INSERT INTO `sistema_de_cadastro_de_personagem`.`parametro_raca`
(`NOME_RACA`)
VALUES
('Aarakocra'),
('Aasimar'),
('Anão'),
('Bugurso'),
('Centauro'),
('Draconato'),
('Duergar'),
('Duplicantes'),
('Eladrin'),
( 'Elfo'),
( 'Elfo Marino'),
( 'Fada'),
(  'Firbolg'), 
( 'Genasi'),
( 'Githyanki'),
( 'Githzerai'),
( 'Gnomo'),
( 'Gnomo das Profundezas'), 
( 'Goblin'),
( 'Golias'),
( 'Halfling'),
( 'Hobgoblins'),
( 'Ikkath'),
( 'Kenku'),
( 'Kobold'),
( 'Laparlonj'),
( 'Meio-Elfo'),
( 'Meio-Orc'),
( 'Minotauro'), 
( 'Morfo'),
( 'Orc'),
( 'Reptante'),
( 'Sátiro'),
( 'Shadar-Kai'),
( 'Tabaxi'),
( 'Tiefling'),
( 'Tortuga'),
( 'Tritões'),
( 'Yuan-ti');
