USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE CLASSE_SALVAGUARDA (
    ID_CLASSE_SALVAGUARDA INT AUTO_INCREMENT,
    ID_CLASSE INT,
    ID_HABILIDADE INT, 
    PRIMARY KEY (ID_CLASSE_SALVAGUARDA)
);