USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE FICHA_PERSONAGEM (
    ID_FICHA_PERSONAGEM INT AUTO_INCREMENT,
    ID_PERSONAGEM INT,
    ID_JOGADOR INT,
    ID_HABILIDADE INT,
    ID_PERICIA INT,
    ID_STATUS_PERSONAGEM INT,
    PRIMARY KEY (ID_FICHA_PERSONAGEM)
    
);