USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE HABILIDADES (
    ID_HABILIDADE INT AUTO_INCREMENT,
    ID_PARAMETRO_HABILIDADE INT,
    VALOR_HABILIDADE INT,
    MODIFICADOR_HABILIDADE INT,
    POSSUI_SALVAGUARDA INT,
    PRIMARY KEY (ID_HABILIDADE)
  
);