USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE PARAMETRO_CLASSE (
    ID_PARAMETRO_CLASSE INT AUTO_INCREMENT,
    NOME_CLASSE VARCHAR(255),
    DADO_DE_VIDA INT, 
    PRIMARY KEY (ID_PARAMETRO_CLASSE)
);