USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE PARAMETRO_HABILIDADE (
    ID_PARAMETRO_HABILIDADE INT AUTO_INCREMENT,
    NOME_HABILIDADE VARCHAR(255),
    PRIMARY KEY (ID_PARAMETRO_HABILIDADE)
);