USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;


CREATE TABLE PARAMETRO_PERICIA (
    ID_PARAMETRO_PERICIA INT AUTO_INCREMENT,
    NOME_PERICIA VARCHAR(255),
    ID_PARAMETRO_HABILIDADE INT,
    PRIMARY KEY (ID_PARAMETRO_PERICIA)
  
);