USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE PERICIAS (
    ID_PERICIA INT AUTO_INCREMENT,
    ID_PARAMETRO_PERICIA INT,
    VALOR_PERICIA INT,
    POSSUI_PERICIA INT,
    PRIMARY KEY (ID_PERICIA)
    
);