USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE PERSONAGEM (
    ID_PERSONAGEM INT AUTO_INCREMENT,
    NOME_PERSONAGEM VARCHAR(255),
    ID_RACA INT, 
    ID_SUB_RACA INT,
    ID_PARAMETRO_CLASSE INT,
    ANTECEDENTE VARCHAR(255), 
    NIVEL INT NOT NULL CHECK (NIVEL BETWEEN 1 AND 30),
    XP INT,
    TIPO_CONJURADOR INT, 
    PRIMARY KEY (ID_PERSONAGEM)
);