USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE RACA_TRACOS_RACIAIS (
    ID_RACA_TRACOS_RACIAIS INT AUTO_INCREMENT,
    ID_RACA INT,
    ID_TRACOS_RACIAIS INT,
    PRIMARY KEY (ID_RACA_TRACOS_RACIAIS)
   
);