USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

CREATE TABLE STATUS_PERSONAGEM (
    ID_STATUS_PERSONAGEM INT AUTO_INCREMENT,
    PONTOS_VIDA_MAXIMA INT,
    PONTOS_VIDA_ATUAL INT,
    PONTOS_VIDA_TEMPORARIA INT,
    CLASSE_ARMADURA INT,
    BONUS_PROFICIENCIA INT,
    PERCEPCAO_PASSIVA INT,
    DESLOCAMENTO VARCHAR(255),
    DADOS_DE_VIDA INT,
    STATUS_MORTE INT,
    TENDENCIA VARCHAR(255),
    PRIMARY KEY (ID_STATUS_PERSONAGEM)
);