USE SISTEMA_DE_CADASTRO_DE_PERSONAGEM;

ALTER TABLE PARAMETRO_PERICIA
ADD CONSTRAINT FK_HABILIDADE_PERICIAS   FOREIGN KEY (ID_PARAMETRO_HABILIDADE) REFERENCES PARAMETRO_HABILIDADE(ID_PARAMETRO_HABILIDADE);